services:
  
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" # RabbitMQ AMQP port
      - "15672:15672" # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  direct_exchange_consumer_microservice:
    image: ${DOCKER_REGISTRY-}directexchangeconsumermicroservice
    build:
      context: .
      dockerfile: Direct_Exchange_Consumer_Microservice/Dockerfile

  direct_exchange_producer_microservice:
    image: ${DOCKER_REGISTRY-}directexchangeproducermicroservice
    build:
      context: .
      dockerfile: Direct_Exchange_Producer_Microservice/Dockerfile

  fanout_exchange_consumer1_microservice:
    image: ${DOCKER_REGISTRY-}fanoutexchangeconsumer1microservice
    build:
      context: .
      dockerfile: Fanout_Exchange_Consumer1_Microservice/Dockerfile

  fanout_exchange_consumer2_microservice:
    image: ${DOCKER_REGISTRY-}fanoutexchangeconsumer2microservice
    build:
      context: .
      dockerfile: Fanout_Exchange_Consumer2_Microservice/Dockerfile

  fanout_exchange_consumer3_microservice:
    image: ${DOCKER_REGISTRY-}fanoutexchangeconsumer3microservice
    build:
      context: .
      dockerfile: Fanout_Exchange_Consumer3_Microservice/Dockerfile

  fanout_exchange_producer_microservice:
    image: ${DOCKER_REGISTRY-}fanoutexchangeproducermicroservice
    build:
      context: .
      dockerfile: Fanout_Exchange_Producer_Microservice/Dockerfile

  headers_exchange_consumer_microservice:
    image: ${DOCKER_REGISTRY-}headersexchangeconsumermicroservice
    build:
      context: .
      dockerfile: Headers_Exchange_Consumer_Microservice/Dockerfile

  headers_exchange_producer_microservice:
    image: ${DOCKER_REGISTRY-}headersexchangeproducermicroservice
    build:
      context: .
      dockerfile: Headers_Exchange_Producer_Microservice/Dockerfile

  topic_exchange_consumer_microservice:
    image: ${DOCKER_REGISTRY-}topicexchangeconsumermicroservice
    build:
      context: .
      dockerfile: Topic_Exchange_Consumer_Microservice/Dockerfile

  topic_exchange_producer_microservice:
    image: ${DOCKER_REGISTRY-}topicexchangeproducermicroservice
    build:
      context: .
      dockerfile: Topic_Exchange_Producer_Microservice/Dockerfile

volumes:
  rabbitmq_data:
    driver: local










